### ISSUE TITLE
请教一下盟主

### ISSUE THREAD

**Issue by macleo** [Jude95/Joy#2]
这个项目，clone回来导入AS，一跑就提示：/Users/Star/AndroidStudioProjects//Joy/app/src/main/java/com/jude/joy/joy/model/callback/DataCallback.java
1.
/Users/Star/AndroidStudioProjects/Joy/app/src/main/java/com/jude/joy/joy/model/callback/DataCallback.java
Error:(15, 74) error: LinkCallback is not public in com.jude.joy.model.callback; cannot be accessed from outside package

将LinkCallback，修改为publlic后，添加了umeng的library，再跑出现2

2.
Error:(12, 23) error: incompatible types: com.jude.joy.joy.model.callback.LinkCallback cannot be converted to com.jude.joy.model.callback.LinkCallback
/Users/Star/AndroidStudioProjects/Joy/app/src/main/java/com/jude/joy/joy/model/callback/LinkCallback.java

我想这个项目应该是不需要修改的吧，特来请教一下盟主，谢谢

**Comment by Jude95** [comment]
。。。这是什么错误，我也不知道啊。本来这些类都是public的吧。clean一下？本来就没多少代码的小APP。
别加友盟的哪个module,有错误，友盟的包也是很老的了。
可能是我把项目文件传到了仓库的后果。你把.idea build app.iml什么的文件都手动删了试试？

**Comment by macleo** [comment]
不加umeng的library，不行的，看你代码里有用到umeng的东西。
盟主的这个项目是AS的吧？好的，那我试试，感谢盟主指点

**Comment by macleo** [comment]
at com.jude.beam.expansion.BeamBaseActivity.setContentView(BeamBaseActivity.java:62) 
                                                     at com.jude.joy.module.main.MainActivity.onCreate(MainActivity.java:40) 
                                                     at android.app.Activity.performCreate(Activity.java:5133) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261) 
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:525) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020016

盟主这样的问题，是少文件么？

**Comment by Jude95** [comment]
呃，看看这些

```
compileSdkVersion 23
buildToolsVersion "23.0.2"

    targetSdkVersion 23

compile 'com.android.support:appcompat-v7:23.2.0'
```

都是23以上。

```
classpath 'com.android.tools.build:gradle:1.5.0'
```

然后clean一下。
（以最新为准）

**Comment by macleo** [comment]
感谢盟主指点
